channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - matplotlib
  - netcdf4
  - opencv
  - pyyaml
  - scikit-learn
  - xarray
  - xgboost
  - tqdm
  - pytorch
  - seaborn